http:
  listener:
    port: "8062"
    readtimeout: "600000"
  request:
    host: "192.168.0.186"
    port: "8063"
    path: 
      register: "/api/customers/registration"
      login: "/api/customers/login"
      verify: "/api/customers/verify"
      reset: "/api/customers/reset"
      resetpassword: "/api/customers/reset/password"
      delete: "/api/customers/delete"
      notify: "/api/notifications"
      getdata: "/api/customers/data"
      postdata: "/api/customers/database"
 